/**
 * Generated by @olonjs/cli. Dev APIs live in scripts/vite/tenantDevApiPlugin.ts
 * (/api/save-to-file, /api/upload-asset, /api/list-assets, WebMCP manifests).
 */
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import path from 'path';
import { fileURLToPath } from 'url';
import { tenantDevApiPlugin } from './scripts/vite/tenantDevApiPlugin';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    tenantDevApiPlugin({ rootDir: __dirname }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      'next/link': path.resolve(__dirname, './src/shims/next-link.tsx'),
    },
  },
  server: {
    fs: {
      allow: [
        path.resolve(__dirname, '..', '..'),
      ],
    },
    watch: {
      usePolling: true,
      interval: 300,
    },
  },
});
